apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2
  namespace: test
  labels:
    app: my-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-2
  template:
    metadata:
      labels:
        app: my-app-2
    spec:
      containers:
        - name: my-app2-container
          image: nginx:latest
          ports:
            - containerPort: 80
