apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-3
  namespace: deneme
  labels:
    app: my-app-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-3
  template:
    metadata:
      labels:
        app: my-app-3
    spec:
      containers:
        - name: my-app3-container
          image: nginx:latest
          ports:
            - containerPort: 80
